---
- hosts: servers

  become: false
  tasks:
    - name: DNF Package Updater
      dnf:
        update_only: yes
        update_cache: yes
    - debug:
        msg: "Days up: {{ (ansible_facts.uptime_seconds / 86400) | int }}"
